### PR TITLE
Add Log Prefix for logs in an instance

### PR DESCRIPTION
**Pull request by ExtremTechniker**
with custom logger
Move all necessary functions from nodecg.log to logger

### CODE REVIEW

**Comment by ExtremTechniker** [comment]
@daniel0611 Could you please resolve these merge conflicts, because I do not have write accesses to do this. Thanks!

**Comment by daniel0611** [comment]
Sure, no problem!

**Comment by Tim-Tech-Dev** [comment]
I want to mention that there are 4 test cases failing.

**Comment by daniel0611** [comment]
Yeah, because the logger is now passed to `createClient` etc. and the current test check for the passed arguments for the config. I'll fix it soon.

**Comment by Tim-Tech-Dev** [comment]
> Wondering if these test failures were here before the merge. I can't remember.
Yes

Also, I looked at this commit history and want to mention that this will cause problems with git blame and other tools. Because the contents of the master branch are duplicated.

**Comment by daniel0611** [comment]
What do you mean with "duplicated"? Because of 755ae357d1cf9ce8179a751fd44e939b1e8e1ad5? GitHub shows the new changes from the other branch in merge commits that resolved conflicts. This is not the case when using `git diff` locally and blame is still working fine on this branch aswell: https://github.com/codeoverflow-org/nodecg-io/blame/9ea7a6b6d138e3960892828eb47cb41bfa4bf59f/services/nodecg-io-ahk/extension/index.ts
Anyways I'm gonna squash merge this PR for cleaner history becasue of the 4 fixup commits.

**Pull request merged**
