### PR TITLE
feat/NodeCG-CI

### PR DESCRIPTION
**Pull request by Tim-Tech-Dev**
Minimize runtime errors by actually trying to run our
framework with NodeCG. This CI will run on push and
pull requests to the main branch.

As suggested in the discussion following #325.

### CODE REVIEW

**Comment by Tim-Tech-Dev** [comment]
The action is failing because NodeCG wants to write to folders it should not.

https://github.com/Tim-Tech-Dev/nodecg-io/runs/4292590810

**Comment by daniel0611** [comment]
NodeCG only seems to work when given a absolute path to the bundle directories, at least if the bundle directories are in nested sub directories. To fix this we can provide the full path using the main directory you currently already log at the beginning: https://github.com/daniel0611/nodecg-io/commit/b37785373df4f90d708e3eca93bc4836dbb985ac.
I would recommend integrating this check into our current CI check. Both check that our project can be compiled and having two seperate workflows for this don't really provide an advantage other than the workflow without the NodeCG run check runs a bit faster.

**Comment by Tim-Tech-Dev** [comment]
I would suggest using the `$GITHUB_WORKSPACE` [environment variable](https://docs.github.com/en/actions/learn-github-actions/environment-variables). So we don't rely on the path of the runner.

**Comment by Tim-Tech-Dev** [comment]
I missed the `working-directory` values in my commit.

**Comment by Tim-Tech-Dev** [comment]
Added the NodeCG runt to the publishing requirements.

**Review by daniel0611 — APPROVED** [review]
Thank you very much

**Pull request merged**
